In [ ]:
# At its core numpy is all about nd array and data manipulation

import numpy as np

# 2D array
arr1 = np.array([[1,2,3,4],[1,2,3,4]])
print(arr1.shape)

# 1D array
arr = np.array([1,2,3])
print(arr.shape)
print(type(arr))
print(type(arr1))

arr.reshape(1,3)

(2, 4)
(3,)
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


array([1, 2, 3])

In [20]:
arr1 = np.array([1,2,3,4], dtype=np.int64)
arr2 = np.array([2,3,3,4], dtype=np.int64)
print(arr1+arr2)
print(arr1*arr2)
print(arr1/arr2)
print(arr1//arr2)
print(arr1%arr1)
print(arr1^arr2)
print(arr1**arr2)

[3 5 6 8]
[ 2  6  9 16]
[0.5        0.66666667 1.         1.        ]
[0 0 1 1]
[0 0 0 0]
[3 1 0 0]
[  1   8  27 256]


In [33]:
# complex numbers
arr1 = np.array([1+2j, 3, 5+1j],dtype='complex')
arr2 = np.array([1+2j, 3, 5+1j],dtype='complex')
print(arr1+arr2)
print(arr1*arr2)
print(np.sqrt(arr1))
arr = np.array([1,2,3])
print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))

[ 2.+4.j  6.+0.j 10.+2.j]
[-3. +4.j  9. +0.j 24.+10.j]
[1.27201965+0.78615138j 1.73205081+0.j         2.24711143+0.22250788j]
[ 2.71828183  7.3890561  20.08553692]
[0.84147098 0.90929743 0.14112001]
[0.         0.69314718 1.09861229]


In [27]:
identityMatrix = np.eye(10)
onesMatrix = np.ones((5,10))
zerosMatrix = np.zeros((5,10))
print(identityMatrix)
print()
print(onesMatrix)
print()
print(zerosMatrix)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [28]:
# Attributes of nd array

arr = np.array([[1,2,3],[4,5,6]])

print(arr.shape) #(2,3)
print(arr.ndim)  #2
print(arr.size)  # 2*3 = 6
print(arr.dtype) # varies with system
print(arr.itemsize) # varies with system

(2, 3)
2
6
int64
8


In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0][0])
print(arr)
print(arr[0][1:])
print(arr[1::,1::])
print(arr[1:][1:])

1
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 3]
[[5 6]
 [8 9]]
[[7 8 9]]


In [ ]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(arr[0::2, 1::2])

#syntax -> start:stop:step -> []
# slicing happens for each [] arr[1:][1:] -> nexarr[1:] where newarr = arr[1:] -> ans = arr[2:]

[[ 2  4]
 [12 14]]


In [ ]:
# data manipulation -> possible
arr = np.array([1,2,3])
arr[0] = 10
print(arr)

[10  2  3]


In [54]:
# statistical concepts

data = np.array([1,2,3,4])
mean = np.mean(data)
std = np.std(data)
normalized_data = (data-mean)/std
print('Normalized data: ', normalized_data)

Normalized data:  [-1.34164079 -0.4472136   0.4472136   1.34164079]


In [64]:
# logical operations

data = np.array([1,2,3,4,5,6,7,8,9])
print(data[data>7])

data = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(data[data>3])
for x in data[((data>5) & (data <10))]:
    print(x,end='-')

[8 9]
[ 4  5  6  7  8  9 10 11 12 13 14 15]
6-7-8-9-